/**
 * Pro templates from prolink-templates-main (excluding /terminal).
 * Keep in sync with client/src/data/proTemplatesExtended.js
 */

const { PRO_TEMPLATE_ASSETS: IMG } = require('./proTemplateAssets');

const EXTENDED_PRO_TEMPLATES = {
  artist: {
    id: 'artist',
    name: 'Artist',
    category: 'Pro',
    description: 'Neon hero card, track list, tour dates, and platform grid.',
    buttonStyle: 'pill',
    fontFamily: 'display',
    linkLayout: 'list',
    productLayout: 'grid',
    colors: { background: '#08060f', foreground: '#ffffff', accent: '#ec4899', card: 'rgba(255,255,255,0.05)' },
    pageBadge: '● Live now on tour',
    eyebrowLabel: '',
    avatar: IMG.artist.avatar,
    backgroundImage: IMG.artist.backgroundImage,
    shopSectionTitle: 'Listen everywhere',
    shopSectionEyebrow: '',
    pullQuote: '',
    pressLine: '',
    heroCaption: '',
    highlightStats: [],
    ritualSteps: [],
    bio: 'Melodic techno, after-hours warmth, and basslines you feel in your ribcage.',
    blocks: [
      { type: 'header', title: 'Latest tracks', active: true },
      { type: 'link', title: 'Afterglow', subtitle: '3:42', url: 'https://example.com', tag: 'NEW SINGLE', icon: 'play', leading: 'icon', cardVariant: 'offer', active: true },
      { type: 'link', title: 'Midnight Cascade', subtitle: '4:18', url: 'https://example.com', icon: 'play', active: true },
      {
        type: 'tourDates',
        active: true,
        title: 'Tour 2026',
        items: [
          { date: 'MAY 30', city: 'Berlin — Watergate', ticketLabel: 'Tickets', url: 'https://example.com' },
          { date: 'JUN 07', city: 'Paris — Rex Club', ticketLabel: 'Tickets', url: 'https://example.com' },
        ],
      },
      {
        type: 'platformGrid',
        active: true,
        title: 'Listen everywhere',
        items: [
          { title: 'Spotify', subtitle: '412k listeners', url: 'https://open.spotify.com' },
          { title: 'Apple Music', subtitle: 'Editorial playlist', url: 'https://example.com' },
        ],
      },
    ],
    productCards: [],
    seo: { title: 'Artist — Music link in bio', description: 'Tracks, tour dates, and streaming.' },
  },
  brutalist: {
    id: 'brutalist',
    name: 'Brutalist',
    category: 'Pro',
    description: 'Bold borders, numbered link blocks, newsletter CTA.',
    buttonStyle: 'square',
    fontFamily: 'inter',
    linkLayout: 'list',
    productLayout: 'grid',
    colors: { background: '#f4f1ea', foreground: '#000000', accent: '#ff5722', card: '#ffffff' },
    pageBadge: 'Profile · v3',
    eyebrowLabel: 'Producer · DJ · Berlin',
    avatar: IMG.brutalist.avatar,
    pullQuote: '',
    pressLine: '',
    heroCaption: '',
    highlightStats: [],
    ritualSteps: [],
    bio: 'Hard-edged electronics. Half studio rat, half stage animal.',
    blocks: [
      { type: 'link', title: 'NEW SINGLE', subtitle: 'Out now', url: 'https://example.com', leading: 'number', cardVariant: 'colorBlock', listNum: '01', cardColor: '#ff5722', linkColor: 'orange', active: true },
      { type: 'link', title: 'TOUR 2026', subtitle: '12 cities', url: 'https://example.com', leading: 'number', cardVariant: 'colorBlock', listNum: '02', cardColor: '#ffeb3b', linkColor: 'yellow', active: true },
      { type: 'newsletter', title: 'Newsletter', description: 'Monthly drops', url: '', shadowColor: '#ff5722', labelColor: '#ffeb3b', boxBg: '#000000', active: true },
    ],
    productCards: [],
    seo: { title: 'Brutalist — Bold link in bio', description: 'Numbered brutalist links.' },
  },
  coach: {
    id: 'coach',
    name: 'Coach',
    category: 'Pro',
    description: 'Split hero, stats strip, offers with pricing.',
    buttonStyle: 'rounded',
    fontFamily: 'inter',
    linkLayout: 'list',
    productLayout: 'grid',
    colors: { background: '#0f1410', foreground: '#eef0ec', accent: '#c6ff3d', card: 'rgba(255,255,255,0.03)' },
    pageBadge: '● Now coaching',
    eyebrowLabel: 'CSCS · Strength Coach',
    avatar: IMG.coach.avatar,
    shopSectionTitle: 'Work with me',
    highlightStats: [],
    ritualSteps: [],
    bio: 'I help busy women build serious strength.',
    blocks: [
      {
        type: 'stats',
        active: true,
        items: [
          { value: '10k+', label: 'Clients coached' },
          { value: '7 yrs', label: 'Coaching' },
          { value: '4.9★', label: 'App rating' },
        ],
      },
      { type: 'link', title: 'Book a free intro call', subtitle: '15 min call', url: 'https://example.com', featured: true, leading: 'icon', cardVariant: 'offer', icon: 'calendar', iconBg: '#c6ff3d', iconColor: '#0f1410', active: true },
      { type: 'link', title: '12-Week Program', subtitle: 'Video library', url: 'https://example.com', price: '$89', featured: true, leading: 'icon', cardVariant: 'offer', icon: 'dumbbell', active: true },
    ],
    productCards: [],
    seo: { title: 'Coach — Fitness link in bio', description: 'Programs and coaching.' },
  },
  magazine: {
    id: 'magazine',
    name: 'Magazine',
    category: 'Pro',
    description: 'Editorial masthead, cover image, pull quote, index.',
    buttonStyle: 'square',
    fontFamily: 'display',
    linkLayout: 'list',
    productLayout: 'grid',
    colors: { background: '#ece7df', foreground: '#1a1714', accent: '#7a6e63', card: 'transparent' },
    pageBadge: 'Issue Nº 07',
    eyebrowLabel: 'Photographer · Editor',
    avatar: IMG.magazine.avatar,
    backgroundImage: IMG.magazine.backgroundImage,
    shopSectionTitle: 'Index',
    pullQuote: '',
    heroCaption: '',
    highlightStats: [],
    ritualSteps: [],
    blocks: [
      { type: 'quote', active: true, text: '"I am only interested in the moments that almost weren\'t photographed."' },
      { type: 'caption', active: true, text: 'Plate I · Self-portrait, 2026' },
      { type: 'link', title: 'Cover Story', subtitle: 'Vogue Italia', url: 'https://example.com', tag: 'Cover Story', icon: 'newspaper', active: true },
      { type: 'link', title: 'Solo Exhibition', subtitle: 'Paris', url: 'https://example.com', tag: 'Now Showing', icon: 'camera', active: true },
    ],
    productCards: [],
    seo: { title: 'Magazine — Portfolio link in bio', description: 'Editorial portfolio.' },
  },
  skincare: {
    id: 'skincare',
    name: 'Skincare',
    category: 'Pro',
    description: 'Beauty hero, product grid, ritual steps.',
    buttonStyle: 'pill',
    fontFamily: 'display',
    linkLayout: 'list',
    productLayout: 'grid',
    colors: { background: '#fdf6f0', foreground: '#3a2a25', accent: '#a04a2c', card: 'rgba(255,255,255,0.7)' },
    pageBadge: 'Clean · Vegan',
    eyebrowLabel: 'Founder · Lumiére Skin',
    avatar: IMG.skincare.avatar,
    shopSectionTitle: 'Shop favorites',
    shopSectionEyebrow: 'The Collection',
    pressLine: '',
    ritualSteps: [],
    bio: 'Plant-powered formulas for glowing skin.',
    blocks: [
      { type: 'banner', active: true, left: '4.9 · 2.4k reviews', right: 'As seen in Vogue' },
      { type: 'link', title: 'Shop the line', url: 'https://example.com', featured: true, leading: 'icon', cardVariant: 'offer', icon: 'shopping-bag', active: true },
      {
        type: 'ritual',
        active: true,
        eyebrow: 'The Ritual',
        title: 'Four steps. Five minutes.',
        steps: [
          { step: '01', name: 'Cleanse', note: 'Gel Cleanser' },
          { step: '02', name: 'Treat', note: 'Serum' },
        ],
      },
      { type: 'newsletter', title: 'Glow Letter', description: 'Monthly notes', url: '', active: true },
    ],
    productCards: [
      { title: 'Golden Hour Serum', tagline: 'Vitamin C', price: '$58', badge: 'Hero', image: IMG.skincare.productImages[0], url: 'https://example.com' },
      { title: 'Cloud Cream', tagline: 'Ceramide', price: '$44', badge: 'New', image: IMG.skincare.productImages[1], url: 'https://example.com' },
      { title: 'Morning Gel Cleanser', tagline: 'Green tea', price: '$32', image: IMG.skincare.productImages[2], url: 'https://example.com' },
      { title: 'Pink Clay Mask', tagline: 'Detox mask', price: '$36', image: IMG.skincare.productImages[3], url: 'https://example.com' },
    ],
    seo: { title: 'Skincare — Beauty link in bio', description: 'Clean skincare shop.' },
  },
};

module.exports = { EXTENDED_PRO_TEMPLATES };
